// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID           uuid.UUID `json:"id"`
	FileID       string    `json:"file_id"`
	BucketID     string    `json:"bucket_id"`
	Owner        uuid.UUID `json:"owner"`
	Name         string    `json:"name"`
	Size         string    `json:"size"`
	Favourite    bool      `json:"favourite"`
	FileType     string    `json:"file_type"`
	LastModified string    `json:"last_modified"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Email          string    `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}
