// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFile(ctx context.Context, fileID string) error
	GetFile(ctx context.Context, id uuid.UUID) (File, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error)
}

var _ Querier = (*Queries)(nil)
