// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: service_dropbyte.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Dropbyte_CreateUser_FullMethodName = "/pb.Dropbyte/CreateUser"
	Dropbyte_LoginUser_FullMethodName  = "/pb.Dropbyte/LoginUser"
)

// DropbyteClient is the client API for Dropbyte service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DropbyteClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type dropbyteClient struct {
	cc grpc.ClientConnInterface
}

func NewDropbyteClient(cc grpc.ClientConnInterface) DropbyteClient {
	return &dropbyteClient{cc}
}

func (c *dropbyteClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Dropbyte_CreateUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropbyteClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, Dropbyte_LoginUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DropbyteServer is the server API for Dropbyte service.
// All implementations must embed UnimplementedDropbyteServer
// for forward compatibility
type DropbyteServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedDropbyteServer()
}

// UnimplementedDropbyteServer must be embedded to have forward compatible implementations.
type UnimplementedDropbyteServer struct {
}

func (UnimplementedDropbyteServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedDropbyteServer) LoginUser(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (UnimplementedDropbyteServer) mustEmbedUnimplementedDropbyteServer() {}

// UnsafeDropbyteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DropbyteServer will
// result in compilation errors.
type UnsafeDropbyteServer interface {
	mustEmbedUnimplementedDropbyteServer()
}

func RegisterDropbyteServer(s grpc.ServiceRegistrar, srv DropbyteServer) {
	s.RegisterService(&Dropbyte_ServiceDesc, srv)
}

func _Dropbyte_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropbyteServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropbyte_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropbyteServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dropbyte_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropbyteServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dropbyte_LoginUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropbyteServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dropbyte_ServiceDesc is the grpc.ServiceDesc for Dropbyte service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dropbyte_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Dropbyte",
	HandlerType: (*DropbyteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Dropbyte_CreateUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Dropbyte_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_dropbyte.proto",
}
